### ISSUE TITLE
Add bootstrap to config validators to built-in

### ISSUE THREAD

**Issue by vuongxuongminh** [kartik-v/yii2-validators#1]
I suggest add bootstrap to config validators to `\yii\validators\Validator::$builtInValidators` for easier define rules and friendly syntax.

**Comment by kartik-v** [comment]
Thanks. Could you please submit a PR?

**Comment by vuongxuongminh** [comment]
Yes, I will submit a PR.

**Comment by vuongxuongminh** [comment]
Resolved
